my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: copper-axiom-326903
      dataset: dbt_taxi
      threads: 4 
      keyfile: "{{ env_var('KEY_FILE') }}"
